### ISSUE TITLE
!join Command

### ISSUE THREAD

**Issue by MrLotU** [UHCBot/UHCBot#6]
Create a `!join` command that does these 3 things:
1. Give the uhc-attendee role to the user
2. Add the user to the whitelist file using Mojang API (to get UUID)
3. Print to the chat: `<username> was added to the list of attendants`

**Comment by MrLotU** [comment]
Also, we need to have a clause for if the response is nil, aka username is non existing

**Comment by Acg1000** [comment]
What do you mean by that, Like if they do not put in a username then it asks them to remember to insert their username afterwards?

**Comment by Alkali-Metal** [comment]
This can just be a simple arg check because there are cool sauce things in Python.

**Comment by Acg1000** [comment]
We have finished the !join command but there is still some polishing to do :)

**Comment by MrLotU** [comment]
We now need to get the users to have the EXACT same discord Nick as their IGN so we can use that to get the whitelist data we need

**Comment by Acg1000** [comment]
Dont we just have to do that manually?

**Comment by MrLotU** [comment]
Maybe. But it has to be done either way

**Comment by Acg1000** [comment]
Lets not do that through the bot because we wouldn't want to work on something that we can easily just do ourselves. We should focus on the white-listing next :)

**Comment by MrLotU** [comment]
**UPDATE:**
Users won't have to add their username behind the `!join`. Instead we will use their Nickname

**Comment by MrLotU** [comment]
Added once #12 is merged
