### ISSUE TITLE
!start command

### ISSUE THREAD

**Issue by MrLotU** [UHCBot/UHCBot#7]
A command that can only be used by Admins and will do one of the two options below:
1. Create random teams and divide the players evenly over Voice Chat channels
2. Put players in the Voice Chat channels of the team they chose

**Comment by Alkali-Metal** [comment]
So, I'm not completely sure how you guys are determining who is in each UHC via roles but if people have a generic role for everyone in the server whether or not they are partaking in the UHC itself what you would need to do is collect a database of all the people who are partaking in the UHC (can be done via command) and then randomly sort them from that database. Now, you don't really need any special database like RethinkDB or anything like that, this could be easily stored either in the code itself or in a .json file.

**Comment by Acg1000** [comment]
Could we not just have a rank that is given out with an activation command like "!join". Then the teams are picked randomly from the people with that rank if we use another command like "!randometeams"?

**Comment by Alkali-Metal** [comment]
Yes you could, that is possible but it will also require removing the role from everyone whom has it at the end. Most likely via a command like `!endUHC`. But clearing a database would be much easier to code from experience, especially if that database is a `.json` file as that can just be completely overwrote from the code. and if you plan on implementing the auto-`whitelist.json` system you will already have the requirements for a json database.

**Comment by Alkali-Metal** [comment]
Although, now that i'm thinking about it you'll need to remove the colour roles from everyone who has it anyway. :/
So doing it via a role might be easier in this circumstance

**Comment by Acg1000** [comment]
Lol yea, If we were not giving people roles then the way to go would defiantly be what you are talking about. But sense we are giving team colors and a specific channel to people who are taking part of the UHC then we might want to find out a way that we could also take away the roles without removing it entirely(If thats even a thing that can exist).

**Comment by Alkali-Metal** [comment]
What do you mean by "removing it entirely" like, the bot? Because removing the bot won't really change anything.

**Comment by Acg1000** [comment]
Basically removing the roles from people that the bot assigned to them in the first place.

**Comment by Alkali-Metal** [comment]
Ah, okay, yeah, one way of doing that is just keeping a log of everyone the bot assigns a role to and what role they were assigned then just read through the list removing said roles.

**Comment by MrLotU** [comment]
I thought we could just do it like this: If someone does `!join <username>` and we send that username to Mojang to get UUID and such for the `whitelist.json` file. We can as well save the Discord Username and add it to an array, than do `for in` magic when `!start` is used and just work around it like that

**Comment by Acg1000** [comment]
Are we (you guys :P) still working on this? Just wanted to ask :)

**Comment by MrLotU** [comment]
Discontinued for now
